### ISSUE TITLE
SEO verification 메타태그, robots.txt, robots meta tag 수정

### ISSUE THREAD

**Issue by Ryan-TheLion** [KernelSquare/Frontend#327]
- [x] verification 메타태그를 layout 에 설정하여 페이지에 전역적으로 적용될 수 있도록 수정
- [x] robots.txt
  - [x] 권한이 필요해서 로그인 하지 않았을 때 접근이 되지 않는 페이지 Disallow 설정 (크롤링 예산에 긍정적인 영향을 주어 한번에 보다 많은 사이트를 수집할 수 있도록 하는 효과를 기대)
- [x] robots meta
  - [x] 권한이 필요해서 로그인 하지 않았을 때 접근이 되지 않는 페이지가 검색엔진에 노출되지 않도록(색인되지 않도록) noindex 설정
